# Generated by Django 3.2.5 on 2021-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emailid', models.EmailField(max_length=70)),
                ('mobilenumber', models.IntegerField()),
                ('currentcity', models.CharField(max_length=80)),
                ('qualification', models.CharField(max_length=80)),
                ('qualification_dept', models.CharField(max_length=80)),
                ('yearpassedout', models.IntegerField()),
                ('college_name', models.CharField(max_length=80)),
                ('college_university', models.CharField(max_length=80)),
                ('college_location', models.CharField(max_length=80)),
                ('sslc_marks', models.IntegerField()),
                ('hsc_marks', models.IntegerField()),
                ('degree_marks', models.IntegerField()),
                ('arrears_count', models.IntegerField()),
                ('gender', models.CharField(max_length=80)),
            ],
        ),
    ]
