# Generated by Django 3.2.5 on 2021-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210708_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobilenumber',
            field=models.CharField(max_length=12),
        ),
    ]
